### ISSUE TITLE
import_data/sptensor: Check dimensions on import

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#11]
The `import_data` method does not check if the indices provided in a `sptensor` file are valid.

Here is some data from a file:
```bash
$ more sptensor2.tns 
sptensor
3 
3 3 1 
3
1 1 1 1
1 3 2 22
2 2 2 3
```
And here is an example of not checking for valid indices. We can load the data, even though it contains indices that are out of bounds on the third dimension of both of the last two nonzeros in the file:
```bash
$ python
>>> import pyttb as ttb
>>> S = ttb.import_data('sptensor2.tns')
>>> S
Sparse tensor of shape (3, 3, 1) with 3 nonzeros 
        [0, 0, 0] = 1.0
        [0, 2, 1] = 22.0
        [1, 1, 1] = 3.0
>>> S[1,1,1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dmdunla/dev/github.com/pyttb/pyttb/sptensor.py", line 1355, in __getitem__
    [subs, shape] = ttb.tt_renumber(subs, self.shape, region)
  File "/Users/dmdunla/dev/github.com/pyttb/pyttb/pyttb_utils.py", line 477, in tt_renumber
    newsubs[:, i], newshape[i] = tt_renumberdim(
  File "/Users/dmdunla/dev/github.com/pyttb/pyttb/pyttb_utils.py", line 514, in tt_renumberdim
    newidx = idx_map[idx]
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by dmdunla** [comment]
@DeepBlockDeepak Example provided for this issue

**Comment by dmdunla** [comment]
@DeepBlockDeepak I suggest you work on this issue next

**Comment by DeepBlockDeepak** [comment]
The shape check will take place inside of `sptensor.from_data()`; all other sptensor class methods like `from_tensor_type()`, `from_function()`, and `from_aggregator()` wind up pointing to `from_data()`, as does the `import_data()` utility.

**Comment by DeepBlockDeepak** [comment]
Post-sub check, using same data as above, with `sptensor2.tns`:
```bash
$ python
>>> import pyttb as ttb
>>> S = ttb.import_data('sptensor2.tns')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jmeds/code/pyttb/pyttb/import_data.py", line 52, in import_data
    return ttb.sptensor.from_data(subs, vals, shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jmeds/code/pyttb/pyttb/sptensor.py", line 167, in from_data
    raise ValueError(f"Index out of bounds: {idx} for dimension: {i}")
ValueError: Index out of bounds: 1 for dimension: 2
```
