### ISSUE TITLE
sptensor: `__init__` requires `shape` but `from_aggregator` does not

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#232]
The following should be consistent in required inputs, but currently are not:

```python
>>> import pyttb as ttb
>>> import numpy as np
>>> subs = np.array([[0, 2, 0], [0, 3, 0]])
>>> vals = np.array([[6], [7]])
>>> S = ttb.sptensor.from_aggregator(subs,vals)
>>> S = ttb.sptensor(subs,vals)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dmdunla/dev/github.com/pyttb/pyttb/sptensor.py", line 207, in __init__
    raise ValueError(
ValueError: For non-empty sptensors subs, vals, and shape must be provided
```

*Suggestion:* allow `shape` to be optional in `__init__`, inferring the `shape` as in `from_aggregator`.

**Comment by dmdunla** [comment]
Closed by #243
