### ISSUE TITLE
Issues building documentation locally with `sphinx-build`

### ISSUE THREAD

**Issue by jeremy-myers** [sandialabs/pyttb#249]
The contributing guide states to run
```
sphinx-build ./docs/source ./docs/build
```
to build the documentation locally. However, this seems to fail with the `.ipynb` tutorials. Full stack trace below. Note that I have `pyttb` and all dev/doc dependencies installed in my virtual environment.

```
# Sphinx version: 5.3.0
# Python version: 3.10.11 (CPython)
# Docutils version: 0.18.1 release
# Jinja2 version: 3.1.2
# Last messages:
#   reading sources... [ 61%] sumtensor
#   reading sources... [ 64%] symktensor
#   reading sources... [ 66%] symtensor
#   reading sources... [ 69%] tenmat
#   reading sources... [ 71%] tensor
#   reading sources... [ 74%] tensor_classes
#   reading sources... [ 76%] ttensor
#   reading sources... [ 79%] tuckerals
#   reading sources... [ 82%] tutorial/CP_APR
#   ~/pyttb/docs/source/tutorial/CP_APR.ipynb: Executing notebook using local CWD [mystnb]
# Loaded extensions:
#   sphinx.ext.mathjax (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.4) from /usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.1) from /usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.13) from /usr/local/lib/python3.10/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc.typehints (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/typehints.py
#   sphinx.ext.autodoc (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.napoleon (5.3.0) from /usr/local/lib/python3.10/site-packages/sphinx/ext/napoleon/__init__.py
#   myst_nb (0.17.2) from /usr/local/lib/python3.10/site-packages/myst_nb/__init__.py
#   sphinx_rtd_theme (unknown version) from /usr/local/lib/python3.10/site-packages/sphinx_rtd_theme/__init__.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1263, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/site-packages/nbclient/util.py", line 85, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/nbclient/util.py", line 60, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.10/3.10.11/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 701, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1019, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 913, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import sys
import pyttb as ttb
import numpy as np
------------------

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [1], line 3
      1 import os
      2 import sys
----> 3 import pyttb as ttb
      4 import numpy as np

ModuleNotFoundError: No module named 'pyttb'
ModuleNotFoundError: No module named 'pyttb'


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/local/lib/python3.10/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 310, in build_update
    self.build(to_build,
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 326, in build
    updated_docnames = set(self.read())
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 433, in read
    self._read_serial(docnames)
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 454, in _read_serial
    self.read_doc(docname)
  File "/usr/local/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 510, in read_doc
    publisher.publish()
  File "/usr/local/lib/python3.10/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/local/lib/python3.10/site-packages/sphinx/io.py", line 104, in read
    self.parse()
  File "/usr/local/lib/python3.10/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/lib/python3.10/site-packages/myst_nb/sphinx_.py", line 150, in parse
    with create_client(
  File "/usr/local/lib/python3.10/site-packages/myst_nb/core/execute/base.py", line 83, in __enter__
    self.start_client()
  File "/usr/local/lib/python3.10/site-packages/myst_nb/core/execute/direct.py", line 50, in start_client
    raise ExecutionError(str(self.path)) from result.err
myst_nb.core.execute.base.ExecutionError: ~/pyttb/docs/source/tutorial/CP_APR.ipynb
```

**Comment by ntjohnson1** [comment]
Hmm not being able to import pyttb makes me suspicious of the environment, since our read the docs uses the same configuration. Can you check where your sphinx-build is running from and where pyttb is importing from in your environment?

**Comment by jeremy-myers** [comment]
@ntjohnson1 Clean reinstall doing `python3 -m pip install -e ".[dev,doc]" --ignore-installed` did the trick.
